### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by wangtao-hku** [jzhangbs/DTUeval-python#2]
Hi, thanks for the code.  just tried to run the code and set it to pcd instead of mesh.

But i encountered a memory error. Any suggestions? 

Many thansks

error
 File "sklearn\neighbors\_binary_tree.pxi", line 1591, in sklearn.neighbors._kd_tree.BinaryTree.query_radius
  File "sklearn\neighbors\_binary_tree.pxi", line 1547, in sklearn.neighbors._kd_tree.BinaryTree.query_radius
MemoryError
downsample pcd:  25%|█████████████████████████████▊                                                                                         | 2/8 [07:27<22:21, 223.50s/it]

also, i found the scale of point clouds produced by colmap is totally different to the dtu dataset. wondering if you preprocessed the colmap dense reconstruction or scale it up before using the code?

**Comment by jzhangbs** [comment]
Hi, the error message doesn't give much information. Maybe it's just Out f Memory issue.

**Comment by wangtao-hku** [comment]
> 

Hi, thanks for you reply, it works when i use another point cloud, so assuming the previous one is broken.

However, after 2 days search, i found the size of the ply produced by colmap has random scale factor that i found impossible to compare with the DTU dataset which possesses the right depth parameters.

Wondering if there is any modification on the colmap such that i am able to compare with the benchmark?

Any help is much appreciated.
